#!/usr/bin/expect -f

set timeout 3
set password "Grad123!\$"

spawn ssh nbhtd@hellbender.rnet.missouri.edu "squeue -j 12415351 -o '%.18i %.9P %.20j %.8u %.2t %.10M %.6D %R'"

expect {
    -re "(password|Password):" {
        send "$password\r"
        exp_continue
    }
    "Permission denied" {
        puts "Authentication failed"
        exit 1
    }
    timeout {
        puts "Connection timed out"
        exit 1
    }
    eof
}

wait
