#!/usr/bin/expect -f

set timeout 3
set password "Grad123!\$"

spawn ssh nbhtd@hellbender.rnet.missouri.edu "cd ~/melsi_simulations/hellbender && sbatch skiome_omnibus_job.sh"

expect {
    -re "(password|Password):" {
        send "$password\r"
        exp_continue
    }
    "Permission denied" {
        puts "Authentication failed"
        exit 1
    }
    timeout {
        puts "Connection timed out"
        exit 1
    }
    eof
}

wait
