#!/usr/bin/expect -f

set timeout 3
set password "Grad123!\$"

spawn scp skiome_omnibus_only.R nbhtd@hellbender.rnet.missouri.edu:~/melsi_simulations/hellbender/

expect {
    -re "(password|Password):" {
        send "$password\r"
        exp_continue
    }
    "Permission denied" {
        puts "Authentication failed"
        exit 1
    }
    timeout {
        puts "Connection timed out"
        exit 1
    }
    eof
}

wait
